name: Metal Prices Mail

on:
  schedule:
    - cron: "0 5 * * 1-5"   # 8:00 TR
    - cron: "30 5 * * 1-5"   # 8:30 TR
    - cron: "0 6 * * 1-5"   # 9:00 TR
    - cron: "0 19 * * 1-5"   # 22:00 TR
   
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install yfinance pandas openpyxl pytz

      - run: python main.py
        env:
          MAIL_FROM: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          MAIL_TO:   ${{ secrets.MAIL_TO }}
