name: Metal Prices Mail
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install yfinance pandas openpyxl pytz
      - run: python main.py
        env:
          MAIL_FROM: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          MAIL_TO:   ${{ secrets.MAIL_TO }}
